### ISSUE TITLE
The scaling method is broken.

### ISSUE THREAD

**Issue by LifeWorks** [RuleWorld/bionetgen#210] opened 2019-03-04 16:16 UTC
Hi Jim,

Last week I try to modify a bit about the scaling method (HAS), but it keeps generating "Simulation method 'has' is not a valid option". I think the reimplementation of parsing the "Actions" block may be the reason. I located the changes related to it one commit each time. I suspect the implementation of simulation_protocol affected it.

But when I read the code, it seems fine to me. Would you mind check it? I checked the scaling method using the Model/heterogeneous_adaptive_scaling.bngl file proved.

 Best! 

Song

**Comment by ASinanSaglam** [comment] 2019-03-14 18:42
Hi Song,

Correct me if I'm wrong but I suspect you are trying to run this with BioNetGen from your fork of the repo? Because I tested that file with our current distribution and it works without any issues for me. 

I took a look at your fork of the repo I believe you only changed the Perl scripts that's calling "HAS" to PSA, however, that's not the only place where they are defined. In fact, you specifically need to change the C++ code (see [run_network.cpp](https://github.com/RuleWorld/bionetgen/blob/master/bng2/Network3/src/run_network.cpp) and related files in folder [Network3](https://github.com/RuleWorld/bionetgen/tree/master/bng2/Network3/src)) if you want to modify the HAS method. If you do this, you need to rebuild the code following the [instructions on the main page of our repo](https://github.com/RuleWorld/bionetgen#compilation-from-source). 

Please let me know if there is something else I'm missing. I will close this issue in a few days unless there is another issue you have encountered that we can reproduce. 

Best,

**Comment by LifeWorks** [comment] 2019-03-14 22:01
I have changed the run_network accordingly. And it is actually not the problem of run_network.cpp. 

I tested with the master branch. It is broken. The BioNetGen 2.4.0 is probably working.

**Comment by ASinanSaglam** [comment] 2019-03-14 22:05
BioNetGen2.4.0 is built off of master branch of RuleWorld/bionetgen, that's why I'm not sure how to reproduce the issue you mentioned.

**Comment by LifeWorks** [comment] 2019-03-17 01:21
I used linux. Also can you just git clone the current master branch rather than using BioNetGen 2.4.0? BNG2.4.0 is OK, the problem is happening with the master branch. If there is no problem when you using the current master branch then it is probably the problem of my side.

**Comment by ASinanSaglam** [comment] 2019-03-17 01:38
Sure, I'll give that a try soon, latest Monday by the end of the day. Just to clarify though, the 2.4.0 is compiled from [this commit](cf9a69c227dced01874be7cc121ba38453a85c31) which is very recent. So if there is an issue with a compilation from the current master branch, this means that the issue is very recently introduced (8 commits since January of this year) and we should be able to track the issue to one of those.

Either way, thank you very much for testing your changes out and helping out with testing the current repo, it is much appreciated!

**Comment by ASinanSaglam** [comment] 2019-03-17 03:01
I git cloned a fresh copy, compiled it and ran the `heterogeneous_adaptive_scaling.bngl` test case and it's working fine on my end.

**Comment by lh64** [comment] 2019-04-02 23:07
Hi all, I pulled down @LifeWorks' fork, recompiled run_network, and was able to run partial_dynamical_scaling.bngl. I'm attaching the screen output here. There was one problem, an argument named `popscale`, which is getting a default value of 100 on the Perl side, is getting passed to run_network but it doesn't recognize it. It gets through that somehow though and finishes the run. So that needs to be fixed but it doesn't appear to be a fatal error so I'm not quite sure what the issue is. Just wanted to let you all know.
[test_psa_screen_output.txt](https://github.com/RuleWorld/bionetgen/files/3036202/test_psa_screen_output.txt)

**Comment by lh64** [comment] 2019-04-02 23:26
Just a quick follow up. I looked in run_network.cpp and on line 279 the long option is called "poplevel". I assume changing it to "popscale" will solve the problem. Also, on line 309 there's no exit command after that error message that's getting thrown. I'll go ahead and fix that in the RuleWorld master and push it there.

**Comment by LifeWorks** [comment] 2019-04-05 23:07
Hi @lh64, did you fix the problem? I think what we want is to change the name to "poplevel" at least at the perl side. It does not matter too much what the name in run_network.cpp as long as it can get the poplevel value in and do the simulation right, however change it to "poplevel" is better in terms of consistency about names.

The default values is deliberately assign in case anyone want to use psa method but forget to provide target "poplevel", maybe it is not necessary.

**Comment by LifeWorks** [comment] 2019-04-05 23:09
@lh64 , please change the "popscale" in the test file to "poplevel" rather than change the name "poplevel" in code to "popscale". "poplevel" is what we want.

**Comment by LifeWorks** [comment] 2019-04-05 23:20
@lh64 Thanks for point it out. I will fix the problem and create the new pull request.

**Comment by LifeWorks** [comment] 2019-04-05 23:30
I fixed the problem and created new pull request. Now it should right and working as expected.

**Closed** 2019-04-05 23:31 UTC
