### ISSUE TITLE
Invalid Bond error message for two sample models.

### ISSUE THREAD

**Issue by rhclark** [RuleWorld/bionetgen#154] opened 2015-09-22 21:48 UTC
The two data files catalysis.bngl  and  energy_example2.bngl  are causing BioNetGen to return the message: "Invalid bond: Bond 1 is assigned to more than one binding site".  These files are found in the samples directory of the RuleBender distribution package.

**Comment by jjtapia** [comment] 2015-09-22 22:08
The error message is printed by https://github.com/RuleWorld/bionetgen/blob/master/parsers/BNGParser/src/bngparser/dataType/BondList.java inside the BNGparser. I'll look into it

**Comment by lh64** [comment] 2015-09-22 23:54
So BioNetGen itself is not returning this error, correct? This is coming from the BNGParser? I can't replicate the error in either RB 2.0.382 or 2.0.404. Is there a new version using an updated version of the BNGParser? I also don't see a model called 'energy_example2.bngl'. I see 'energy_example1.bngl'. Is that the one that you're referring to?

**Comment by jjtapia** [comment] 2015-09-23 00:08
Yes, these are BNGParser errors. They appear in the system console from which Rulender is invoked BTW, not in the Rulebender console. They appear in both the latest releases of 2.0.x and 2.1.x. The relevant portions of the BNGParser haven't been updated in a while so they are bound to appear in previous versions as well. 

Mind you, this is more of a warning from the parser than a showstopper bug, so that's why I gave it a low priority. I'll get to it before the next release though. (comming soon (TM))

**Comment by lh64** [comment] 2015-09-23 00:10
Why am I not seeing them in 2.0.382 or 2.0.404 then? Are they not getting piped into the RB console in older versions or something?

**Comment by jjtapia** [comment] 2015-09-23 00:12
They should appear into your system console. (cmd in windows, shell/bash in MacOSX/Linux). They  do not appear in the RB console.

**Comment by lh64** [comment] 2015-09-23 00:16
I see. So is the error real? Is there really a bond assigned to more than one binding site? Or is there an error in BNGParser making it throw an error when it shouldn't?

**Comment by lh64** [comment] 2015-09-23 00:17
Looking through the model files, I don't see anything obviously wrong.

**Comment by jjtapia** [comment] 2015-09-23 00:21
Ok I tracked it down. The problem seems to be related to the namespace of bond numbers in the energy patterns section

begin energy patterns
    S(e!2).kinase(s!2)  Gf_S_kinase/RT  # substrate-kinase binding
    S(e!2).pptase(s!2)  Gf_S_pptase/RT  # substrate-pptase binding
end energy patterns

It would seem that instead of having the bond namespace to be restricted on a per species scope, it is extending it to the entire energy patterns section, which makes it believe that g the same bond number is being reused for different binding definitions. This seems to only happen within energy patterns though (observables, seed species, reaction rules are always working as intended) so I'll look into what makes it different. Probably the method that checks for bond number consistency is getting passed the wrong array, or that array is being maintained incorrectly.

**Comment by jjtapia** [comment] 2015-09-23 01:01
Solved in commit c0277643895763970f43c7582eb967cbe090c08e. The parser passes its own test . Please test if the problem is solved on your side Rob.

**Comment by rhclark** [comment] 2015-09-23 14:41
Yup !!  I rebuilt the parser, rebuilt RuleBender and I reran those two simulations.  I got no error messages, so I believe that the bug is fixed.  That was fast !!  This issue can be closed if you wish.

**Closed** 2015-09-23 14:42 UTC
Labels: bug, Priority-Low
